### ISSUE TITLE
Wrong artist id

### ISSUE THREAD

**Issue by rxrdev** [DmitryMironchenko/case-study-apollo-server#1]
https://github.com/DmitryMironchenko/case-study-apollo-server/blob/14cccb53f89dea5a35837c5ffbdc56e80e480354/mocks/car.js#L6
The artist with id `3305` does not exist. I believe it should be replaced with `3505`
See [artists.json](https://github.com/DmitryMironchenko/case-study-apollo-server/blob/master/mocks/artists.json)

**Comment by DmitryMironchenko** [comment]
That's correct! Thank you!

**Comment by DmitryMironchenko** [comment]
Fixed
